server:
  port: 80
#  servlet:
 #   context-path: /root

#定义项目使用到的一些常量
url:
  payNotifyUrl: http://vip.tq.com/setrecord

# mybatis
mybatis:
  type-aliases-package: com.simons.cn.springbootdemo.bean
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mybatis/mapper/*/*.xml

# druid
spring:
  datasource:
    url: jdbc:mysql://118.190.104.220:3306/simons?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    content-type: text/html
  redis:
    host: 118.190.104.220
    port: 6379
    password: 123456
    pool:
      max-active: 100
      max-idle: 100
      max-wait: 5000
      timeout: 5000
logging:
  level:
    com.simons.cn.springbootdemo.dao.system:
      debug
